# db
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost/wow_guild}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgresql}
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# server
server.port=9090

# kafka
kafka.servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
kafka.topic.partitions=4

# firebase
firebase.app.keys.file=push-api/firebase-api-keys.json